### PR TITLE
Add a slideshow of games to the landing page

### PR DESCRIPTION
**Pull request by kelo221**

### CODE REVIEW

**Comment by Yusyuriv** [comment]
I'm not sure it's a good idea to feature games like that without asking for permission from their creators. Also, you can see in the diff that that section actually had two backgrounds, one of them was adding black gradients at the top and at the bottom, you removed it.

**Comment by kelo221** [comment]
Black gradient has been returned
https://redot-landing-page.vercel.app/

**Comment by opdev1004** [comment]
I made same mistake when I did mine. I think it needs black gradient at the bottom as well.

**Comment by kelo221** [comment]
Oh, sharp eyes!

**Comment by chrisrabe** [comment]
Looks pretty good. In `MainPageHero.vue` page, can you please replace the "Game Name" with your game's name?

**Comment by kelo221** [comment]
They don't have a name (nor release anywhere), they are simply prototypes I've been trying out. 
They serve as temporary images for showcasing the hero until something more fancy is submitted🙂, so no attribution is required

**Comment by chrisrabe** [comment]
Ah alright. I guess the "Game name" pill can be hidden for now. After that, I'll approve and merge

**Review by chrisrabe — APPROVED** [review]

**Pull request merged**
